version: '3'
services:
    austin-mysql:
        environment:
            TZ: Asia/Shanghai
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: "123456"
        restart: always
        container_name: austin_mysql
        image: mysql:5.7
        hostname: mysql
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        volumes:
            - ./sql/austin.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "23306:2306"
        networks:
            - app
    austin-redis:
        image: redis:3.2
        ports:
            - "16379:6379"
        restart: always
        container_name: austin-redis
        networks:
            - app
    austin:
        build:
            context: ./
        ports:
            - "8080:8080"
        container_name: austin
        depends_on:
            - austin-mysql
            - austin-redis
        networks:
            - app