version: '3'
services:
    austin-mysql:
        environment:
            TZ: Asia/Shanghai
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: "123456"
        restart: always
        container_name: austin_mysql
        image: mysql:5.7
        hostname: mysql
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        volumes:
            - ./sql/austin.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "23306:2306"
        networks:
            - app
    austin-redis:
        image: redis:3.2
        ports:
            - "16379:6379"
        restart: always
        container_name: austin-redis
        networks:
            - app
    austin-kafka:
        image: wurstmeister/kafka
        container_name: kafka
        volumes:
            - "/etc/localtime:/etc/localtime"
        environment:
            KAFKA_BROKEN_ID: 0
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
            KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "austinBusiness:1:1,austinRecall:1:1,austinTraceLog:1:1"
            KAFKA_HEAP_OPTS: -Xmx256M -Xms256M
        ports:
            - "9092:9092"
        depends_on:
            - austin-zookeeper
        networks:
            - app
    austin-zookeeper:
        image: wurstmeister/zookeeper
        container_name: austin-zookeeper
        volumes:
            - "/etc/localtime:/etc/localtime"
        ports:
            - "2181:2181"
    austin-xxl-job:
        image: xuxueli/xxl-job-admin:2.3.0
        container_name: austin-xxl-job
        ports:
            - "6767:6767"
        environment:
            PARAMS: `--spring.datasource.url=jdbc:mysql://austin-mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root  --spring.datasource.password=root123_A'
        networks:
            - app
    austin:
        build:
            context: ./
        ports:
            - "8080:8080"
        container_name: austin
        depends_on:
            - austin-mysql
            - austin-redis
            - austin-kafka
            - austin-zookeeper
            - austin-xxl-job
        networks:
            - app