
spring:
    profiles:
        active: dev
    application:
        name: austin
    datasource:
        url: jdbc:mysql://${austin.database.ip}:${austin.database.port}/austin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: ${austin.database.username}
        password: ${austin.database.password}
        driver-class-name: com.mysql.jdbc.Driver
    rabbitmq:
        host: 172.16.25.234
        port: 15672
        username: guest
        password: guest
        publisher-confirm-type: correlated
        publisher-returns: true
    redis:
        host: ${austin.redis.ip}
        port: 6379
        password: ${austin.redis.password}
austin:
    rabbitmq:
        topic:
            name: austinRabbit
        exchange:
            name: austin.port
server:
    port: 9955

ok:
    http:
        connect-timeout: 30
        keep-alive-duration: 300
        max-idle-connections: 200
        read-timeout: 30
        write-timeout: 30
tencent:
    sms:
        account:
            secret-id: AKIDHRNBnAKH3czCcnkXBdyFOUs6B9uZ2MUM
            secret-key: L3byTwEIAzazEG6o9MP4Y8Xmu211ud9V
            sign-name: 4d348fb534fe55e53f12c984b7742e43
            sms-sdk-app-id: 1400801615
            template-id: 1728494
