server:
    port: 10000

austin:
    redis:
        ip: 172.16.16.106
        port: 6379
        password: 123456
    rabbitmq:
        ip: 172.16.25.234
        port: 15672
    apollo:
        enabled: true
