server:
    port: 10000

austin:
    database:
        ip: austin.mysql
        port: 5004
        username: root
        password: root123
    redis:
        ip: austin.redis
        port: 5003
        password: austin
    rabbitmq:
        ip: localhost
        port: 6379

