spring:
    profiles:
        active: dev
    application:
        name: austin
    datasource:
        druid:
            #数据库地址   172.16.25.234 是mysql服务地址 newwms是数据库名称
            username: root
            password: 123456
            url: jdbc:mysql://172.16.25.234/austin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
            driver-class-name: com.mysql.jdbc.Driver
            max-active: 20
            initial-size: 10
            min-idle: 5
            max-wait: 60000
            pool-prepared-statements: true
            validation-query: SELECT 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            max-pool-prepared-statement-per-connection-size: 20
            use-global-data-source-stat: true
            filters: stat
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 2000
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: true
                login-username: root
                login-password: root
    rabbitmq:
        host: 172.16.25.234
#        port: 15672
        username: guest
        password: guest
        publisher-confirm-type: correlated
        publisher-returns: true
        virtual-host: /
    redis:
        host: ${austin.redis.ip}
        port: 6379
    date:
        format: yyyy-MM-dd HH:mm:ss
    main:
        allow-bean-definition-overriding: true

austin:
    rabbitmq:
        topic:
            name: austinRabbit
        exchange:
            name: austin.port
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
            offset:
                reset: earliest
        topic:
            name: austinKafka
    grayLog:
        ip: 122.112.239.250
    business:
        upload:
            crowd:
                path: /Users/3y/temp
    async:
        task:
            thread-name-prefix: "fun-task-" # task前缀名
            max-size: 8 #最大线程数
            core-size: 4 #核心线程数
            queue-capacity: 100
            keep-alive: 60
            rejected-handler: callrunspolicy #拒绝策略,不能自定义
            allow-core-thread-timeout: true # 是否允许核心线程超时,默认false
            await-termination-seconds: 10 #
            wait-for-tasks-to-complete-on-shut-down: true # 任务执行完,在关闭应用
app:
    id: austin
apollo:
    bootstrap:
        enabled: ${austin.apollo.enabled}
        namespaces: boss.austin
    meta: http://localhost:8080
server:
    port: 9955


ok:
    http:
        connect-timeout: 30
        keep-alive-duration: 300
        max-idle-connections: 200
        read-timeout: 30
        write-timeout: 30
#tencent:
#    sms:
#        account:
#            secret-id: llllllllllllllll
#            secret-key: lllllllllllllll
#            sign-name: 失眠的你Zzz公众号
#            sms-sdk-app-id: 1400801615
#            template-id: 1728494

# 监控配置:
management:
    endpoint:
        health:
            show-details: always
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
      web:
        exposure:
            include: '*'
    metrics:
      export:
        prometheus:
            enabled: true
xxl:
    job:
        admin:
            addresses: http://122.112.239.250:6767/xxl-job-admin        # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
            username:  admin       # 后台用户名
            password:  123456      # 后台密码
        executor:
            appname: austin # 执行器 AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
            ip: # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
            port: 6666 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
            logpath:  # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
            logretentiondays: 30 # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
            jobHandlerName: austinJob
        accessToken:  # 执行器通讯TOKEN [选填]：非空时启用；

##################### wx mp config #####################
wx:
    mp:
        account:
            appid: appid
            secret: secret
            token: token
            aesKey: aesKey